name: Push to Dockerhub

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Publish to Registry (tag)
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          REACT_APP_API_BASE_URL: /
        with:
          name: jonocairns/aubri
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: docker/server.Dockerfile
          tag_names: true
          buildargs: REACT_APP_API_BASE_URL

      - name: Publish to Registry (latest)
        uses: elgohr/Publish-Docker-Github-Action@master
        env:
          REACT_APP_API_BASE_URL: /
        with:
          name: jonocairns/aubri
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          dockerfile: docker/server.Dockerfile
          buildargs: REACT_APP_API_BASE_URL
