name: CI/CD (client/server)

on: 
  push:
    branches:
    - master
    - release/*

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: client install, build, and test
      working-directory: ./client
      run: |
        yarn install
        yarn lint
        yarn build
      env:
        CI: true
    - name: server install, build, and test
      working-directory: ./server
      run: |
        yarn install
        yarn lint
        yarn build
      env:
        CI: true
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      env:
        REACT_APP_AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
        REACT_APP_AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
        REACT_APP_API_BASE_URL: /
      with:
        name: jonocairns/aubri
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: docker/server.Dockerfile
        buildargs: REACT_APP_AUTH0_CLIENT_ID,REACT_APP_AUTH0_DOMAIN,REACT_APP_API_BASE_URL

  
